CREATE TABLE IF NOT EXISTS families (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name text UNIQUE NOT NULL,
	description text NOT NULL,
	created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DO $$ BEGIN
	CREATE TYPE language_status AS ENUM ('living', 'dead', 'proto');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS languages (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	name text NOT NULL,
	autonym text NOT NULL,
	parent_id uuid REFERENCES languages,
	family_id uuid REFERENCES families,
	status language_status NOT NULL,
	era text NOT NULL,
	created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (family_id, name)
);

CREATE TABLE IF NOT EXISTS words (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	word text NOT NULL,
	ipa text NOT NULL,
	meaning text NOT NULL,
	pos text NOT NULL,
	etymology text NOT NULL,
	notes text NOT NULL,
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated timestamptz
);

DO $$ BEGIN
	CREATE TYPE phone_type AS ENUM ('consonant', 'vowel', 'other');
EXCEPTION
	WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS phones (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	base text NOT NULL,
	type phone_type NOT NULL,
	qualities text[] NOT NULL,
	is_allophone boolean NOT NULL,
	allophone_of text NOT NULL,
	is_foreign boolean NOT NULL,
	notes text NOT NULL,
	graph text NOT NULL
);
CREATE INDEX IF NOT EXISTS phones_lang_id_idx ON phones (lang_id);

CREATE TABLE IF NOT EXISTS language_summary_notes (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE PRIMARY KEY,
	description text NOT NULL DEFAULT '',
	phonology_notes text NOT NULL DEFAULT '',
	orthography_notes text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS orthography_settings (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE PRIMARY KEY,
	alphabetical_order text[],
	case_sensitive boolean NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS dictionary_settings (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE PRIMARY KEY,
	show_word_ipa boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS word_classes (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	pos text NOT NULL,
	code text NOT NULL,
	name text NOT NULL,
	UNIQUE (lang_id, pos, code)
);

CREATE TABLE IF NOT EXISTS word_classes_by_word (
	word_id uuid NOT NULL REFERENCES words ON DELETE CASCADE,
	class_id bigint NOT NULL REFERENCES word_classes ON DELETE CASCADE,
	PRIMARY KEY (word_id, class_id)
);

CREATE TABLE IF NOT EXISTS grammar_forms (
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	code text UNIQUE NOT NULL,
	name text NOT NULL
);

CREATE TABLE IF NOT EXISTS phonology_categories (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	letter text NOT NULL,
	members text NOT NULL,
	PRIMARY KEY (lang_id, letter)
);

CREATE TABLE IF NOT EXISTS orthography_categories (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	letter text NOT NULL,
	members text NOT NULL,
	PRIMARY KEY (lang_id, letter)
);

CREATE TABLE IF NOT EXISTS pronunciation_estimation (
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE PRIMARY KEY,
	letter_replacements text NOT NULL,
	rewrite_rules text NOT NULL
);

CREATE TABLE IF NOT EXISTS grammar_tables (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	lang_id uuid NOT NULL REFERENCES languages ON DELETE CASCADE,
	name text NOT NULL,
	pos text NOT NULL,
	rows text[] NOT NULL,
	columns text[] NOT NULL,
	post_rules text NOT NULL DEFAULT '',
	show_ipa boolean NOT NULL,
	invert_classes boolean NOT NULL,
	notes text NOT NULL
);

CREATE TABLE IF NOT EXISTS grammar_table_classes (
	table_id uuid NOT NULL REFERENCES grammar_tables ON DELETE CASCADE,
	class_id bigint NOT NULL REFERENCES word_classes ON DELETE CASCADE,
	PRIMARY KEY (table_id, class_id)
);

CREATE TABLE IF NOT EXISTS grammar_table_cells (
	table_id uuid NOT NULL REFERENCES grammar_tables ON DELETE CASCADE,
	row_index integer NOT NULL,
	column_index integer NOT NULL,
	rules text NOT NULL,
	PRIMARY KEY (table_id, row_index, column_index)
);

CREATE TABLE IF NOT EXISTS grammar_table_irregular_forms (
  table_id uuid NOT NULL REFERENCES grammar_tables ON DELETE CASCADE,
  word_id uuid NOT NULL REFERENCES words ON DELETE CASCADE,
  row_index integer NOT NULL,
  column_index integer NOT NULL,
  form text NOT NULL,
  PRIMARY KEY (table_id, word_id, row_index, column_index)
);
